### ISSUE TITLE
Vertaisarvionti 2

### ISSUE THREAD

**Issue by vaisest** [JonathanHeyno/discussion-threads#2]
Hei, tutustuin sovellukseen Herokussa ja se vaikuttaa toimivan hyvin. Huomasin kuitenkin muutamia asioita:

- Nykyinen ketju/thread ei näy yläosassa navigaatiopalkissa. Välillä oli sekavaa oliko näkymässä ketju vai lista ketjuista. Ilmeisesti ainoa ero on alleviivattu aiheen nimi?
- Navigaatiopalkissa nykyinen näkymä on silti linkki, jota voi klikata, vaikka se vie nykyiselle sivulle.
- Viestit ketjussa ovat nappeja, jotka vaihtavat väriä, kun hiiren vie niiden päälle. Niiden klikkaaminen ei kuitenkaan tee mitään, jos ne eivät ole käyttäjän omia.
- Sivun oikeaa puolta ei juurikaan käytetä. Toki en itse keksi mitä sinne voisi laittaa, mutta tietokoneella se näyttää hieman oudolta.
- Sivupalkissa, jossa on nappeja voisi olla kotinäkymään nappi.

Muuten sovelluksen käytöstä on hankala valittaa. Se toimii nopeasti ja näyttää sekä mukavalta että ainutlaatuiselta. Koodista on seuraavaa palautetta:

- Koodissa ei vaikuta olevan uudelleenohjausta pois esimerkiksi viestin poistamisesta. Esimerkiksi reitissä delete_message on lopussa `render_template`, mikä voisi olla `redirect(url_for("thread"))`. Näin käyttäjän selaimen saa ohjattua uudelle sivulle ja koodikin on siistimpää, sillä tämä tapa käyttää reittien funktioita, eikä suoraan renderöi sivua.
- Koodissa ei ole kommentteja ollenkaan. `Routes.py` ei ole kauhean helppo lukea ja lyhyet kommentit esimerkiksi käsiteltävästä virheestä validoinnissa voisivat olla hyödyllisiä.
- Koodin järjestäminen on toki mielipideasia, mutta vaikuttaa siltä, että tietokantaa koskevat tiedostot on järjestelty esimerkiksi tiedostoihin `users.py` ja `topics.py`, mutta reitit ovat kaikki yhdessä tiedostossa. Koodin siirtäminen esimerkiksi kansioon `users`, jossa on tietokantaa käsittelevä tiedosto ja toinen tiedosto, joka hyödyntää Flaskin blueprintejä saattaisi olla siistimpi vaihtoehto.
- Tietokantaa käsittelevien tiedostojen muuttujien nimeäminen voisi olla selvempää. Esimerkiksi `sql2` vs `insert_message_sql`.

Toiminnallisia ongelmia koodissa ei juurikaan kuitenkaan ole, mikä on hyvä.

**Comment by JonathanHeyno** [comment]
Moi,

Kiitoksia perusteellisesta vertaisarviosta. Mietin samoja asioita itsekin. Kuitenkin

- Päätin olla laittamatta ketjujen ja thredien nimiä navigaatiopalkkiin, sillä ne voivat olla hyvinkin pitkiä ja riippuen käyttäjän ruudun koosta / laitteesta voivat saada sen näkymään sotkuiselta ja viemään esim. kännykässä liikaa ruudun tilasta. Tiedot on nyt laitettu selvemmin näkyviin itse bodyyn jolloin scrollatessa ne eivät haittaa näkyvyyttä jos ovat erittäin pitkiä.
- Ainoastaan viestin kirjoittaja voi muokata viestiä, joten muiden viestejä ei pääse muokkaamaan. Mietin että pitäisikö siirtää käyttäjä jonnekin kun se klikkaa jonkun muun viestiä, mutta en keksi mitä silloin pitäisi tapahtua.
- En laittanut oikeaan reunaan mitään koska en keksi mitä pitäisi laittaa, enkä halua määrittää palkkien sivusuuntaista kokoa koska en tiedä minkä kokoista ruutua / mitä laitetta käyttäjä käyttää joten palkkien määrittäminen tietyn pituisiksi olisi ehkä huono juttu. Lisäksi viestit voivat olla melko pitkiäkin.
- Mietin myös kotinäkymänappia, mutta ajattelin että se on turha koska sen yläpuolella oleva nappi tekee saman asian.

Koodista:

- Vaihdoin renderöinnit redirekteiksi niiltä osin kun täytyy palata login sivulle. Muissa kohdissa renderöinti on mielestäni parempi vaihtoehto redirektille. Esimerkiksi `delete_message`  toiminnossa deletoinnin yhteydessä palautetaan (SQL:n `RETURNING` komennolla) samalla tietokantaoperaatiolla tarvittavat tiedot seuraavan näkymän renderöintiin. Jos renderöinnin sijaan suoritettaisi redirect, haettaisi tarvittavat tiedot toisella tietokantahaulla. Tehtäisi siis turhaan kaksi kertaa enemmän tietokantahakuja.
- Kurssimateriaalissa ei ole selitetty blueprinttien käyttöä enkä ehdi alkaa opettelemaan vaihtoehtoista tapaa tehdä näitä. SQL stringien nimennässä on myös seurattu luentomateriaalien esimerkkejä.
